install:
 - source ./.texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
 
script:
    # Prefix command with travis_wait x so it times out after 3 mins, because when the LaTeX doesn't compile pdflatex just hangs instead of quitting.
  - travis_wait 3 make build
  - travis_wait 3 make pdf


before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "jason-neal"
      - git config --local user.email "jason.neal@astro.up.pt"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

#deploy:
#  provider: releases
#  api_key:
#    secure: GITHUB OAUTH TOKEN ENCRYTPED
#  file:
#  - ./thesis.pdf
#  skip_cleanup: true
#  on:
#    tags: true
#    branch: master
